Tested api and modified update method of course serializer.
iiitv/studybuddy-backend pull request #25
Opened 2020-09-23 16:50 UTC by gaurKrishna

Completed testing of all the api. Modified update method of course serializer to change the course code which is a primary key for that model.

2020-09-24 03:45 UTC, gaurKrishna commented
Added api for Note model and tested the same.

2020-09-24 15:59 UTC, yashshah2820 requested changes
Have implemented the Note Model and where is it needed?

2020-09-24 20:11 UTC, gaurKrishna commented
There is a model named Note in the models.py file in course directory in the original repository and its api were not created so I created its serializer, view and the corresponding url, but if it is not required then I will remove it.

2020-09-25 11:37 UTC, yashshah2820 approved these changes

2020-09-25 11:37 UTC, merged